name: Enforce dev to main

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  only-dev-to-main:
    runs-on: ubuntu-latest
    steps:
      - name: Allow only dev -> main
        run: |
          echo "PR: ${{ github.head_ref }} -> ${{ github.base_ref }}"
          if [ "${{ github.head_ref }}" != "dev" ]; then
            echo "Only merges from 'dev' to 'main' are allowed."
            exit 1
          fi
          echo "OK"
